

################################################################################################
#
# the parameters below will be stored in the variant $context and available for step definitions
#
################################################################################################
---
# you can edit the following location to change the location of test report
# if it's not set, the report will be stored in WORKBOT_ROOT/reports by default
reports_root: #Z:/Foglight

browser: ff
profile: centos64_2612

# you can edit the path to change the location of test report
# if it's not set, the report will be stored in WORKBOT_ROOT/reports by default


# The IP or host name of FTP server
ftp_server: 10.30.149.9

# The FMS host
host: 10.30.154.84

# Agent host
agent_host: zhvmwfg2612

# The URL to access Foglight
server: "http://10.30.154.84:8080"

# Set the default user name and password to login Foglight
default: { user: "foglight", password: "foglight" }

# Specific where to install Foglight
product_installation_path: /home/yammy/Foglight
product_bin_path: /home/yammy/Foglight/product/*build_number*/bin
product_log_path: /home/yammy/Foglight/state/logs

fogflsw01:
  protocol: ftp
  server: 10.30.149.9
  "user name": foglight
  password: foglight
fogflsw02:
  protocol: ftp
  server: 10.30.154.45
  "user name": foglight
  password: foglight


test_machines:
- name: FMS
  host: 10.30.154.84
  log_path: /home/yammy/Foglight/state/logs/