--
# you can edit the following location to change the location of test report
# if it's not set, the report will be stored in WORKBOT_ROOT/reports by default
reports_root: Z:/Foglight

# the following parameters are to configure the FTP server
ftp_server: 10.30.

# the parameters below will store in the variant @context and available for step definitions
browser: chrome
host: 10.30.149.3
agent_host: yammyc_rhel564
server: "http://10.30.149.3:8080"
default: {user: "foglight", password: "foglight"}

foglight_installation_path: /home/yammy/Quest_Software/Foglight

# here to configure your FMS or FglAM install information
test_machines:
- name: FMS
  host: yammyc_rhel564
  log_path: /home/yammy/Quest_Software/Foglight/logs/
#  type: normal
